# Generated by Django 5.1.7 on 2025-03-25 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'permissions': [('view_dashboard', 'Peut voir le tableau de bord'), ('change_entreprise', 'Peut modifier une entreprise'), ('view_entreprise', 'Peut voir les infos entreprise'), ('add_produit', 'Peut ajouter un produit'), ('change_produit', 'Peut modifier un produit'), ('delete_produit', 'Peut supprimer un produit'), ('view_produit', 'Peut voir les produits'), ('manage_promotions', 'Peut gérer toutes les promotions'), ('view_statistics', 'Peut voir les statistiques')]},
        ),
    ]
