# Generated by Django 5.1.7 on 2025-03-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_alter_utilisateur_managers_utilisateur_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
