# Generated by Django 5.1.7 on 2025-04-05 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_alter_utilisateur_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='en_promotion',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Abonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_or_phone', models.CharField(max_length=100)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('promotion', 'Promotion'), ('newsletter', 'Newsletter'), ('alerte', 'Alerte'), ('personnalise', 'Personnalisée')], max_length=20)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('ouverte', models.BooleanField(default=False)),
                ('abonne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promotions.abonne')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.entreprise')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.produit')),
            ],
        ),
        migrations.CreateModel(
            name='VueProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('direct', 'Direct'), ('qr', 'QR Code'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('autre', 'Autre')], max_length=50)),
                ('appareil', models.CharField(blank=True, max_length=100)),
                ('systeme_exploitation', models.CharField(blank=True, max_length=50)),
                ('navigateur', models.CharField(blank=True, max_length=50)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.produit')),
            ],
            options={
                'verbose_name': 'Vue produit',
                'verbose_name_plural': 'Vues produits',
            },
        ),
    ]
