# Generated by Django 5.1.7 on 2025-04-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0006_produit_en_promotion_abonne_notification_vueproduit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='abonne',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='vueproduit',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='en_promotion',
        ),
        migrations.DeleteModel(
            name='Abonne',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='VueProduit',
        ),
    ]
