# Generated by Django 5.1.7 on 2025-05-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0007_remove_notification_abonne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='discount_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
