# Generated by Django 5.1.7 on 2025-05-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0009_remove_produit_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='discount_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
