# Generated by Django 5.1.7 on 2025-05-11 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0012_avisclient_faq_horaireouverture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='discounted_price',
        ),
        migrations.AddField(
            model_name='avisclient',
            name='approuve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='est_expire',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ImageEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='entreprise_images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='promotions.entreprise')),
            ],
        ),
    ]
