# Generated by Django 5.1.7 on 2025-05-12 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0013_remove_produit_discounted_price_avisclient_approuve_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('direct', 'Direct'), ('qr', 'QR Code'), ('social', 'Réseau social'), ('email', 'Email'), ('other', 'Autre')], max_length=50)),
                ('device', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='promotions.produit')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
