# Generated by Django 5.1.7 on 2025-05-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0014_productview'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='categorie_e',
            field=models.CharField(choices=[('Hôtel', 'Hôtel'), ('Supermarché', 'Supermarché'), ('hôpital', 'Hôpital'), ('magasin', 'Magasin'), ('réseau', 'Réseau')], default='Supermarché', max_length=50),
        ),
    ]
