# Generated by Django 5.1.7 on 2025-05-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0015_entreprise_categorie_e'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='description',
            field=models.TextField(default="Soyez à l'afflux de nos meilleurs promos "),
        ),
    ]
