# Generated by Django 5.1.7 on 2025-06-06 14:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0017_activitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entreprise',
            options={'verbose_name': 'Entreprise', 'verbose_name_plural': 'Entreprises'},
        ),
        migrations.AddField(
            model_name='entreprise',
            name='abonnes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='localisation_map',
            field=models.TextField(default=django.utils.timezone.now, help_text="Texte pour l'iframe Google Maps (ex: '6.1234,1.5678' ou 'Nom+du+lieu')"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entreprise',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Description pour le référencement SEO', null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Mots-clés pour le référencement SEO, séparés par des virgules', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='description',
            field=models.TextField(default="Soyez à l'afflux de nos meilleurs promos"),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='localisation',
            field=models.CharField(help_text="Adresse textuelle pour l'affichage", max_length=255),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(choices=[('promo', 'Nouvelle promotion'), ('news', 'Actualité'), ('system', 'Système')], default='promo', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_abonnement', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.entreprise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'entreprise')},
            },
        ),
    ]
