# Generated by Django 5.1.7 on 2025-06-06 21:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0018_alter_entreprise_options_entreprise_abonnes_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAbonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('code_verification', models.CharField(max_length=6)),
                ('est_verifie', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.CreateModel(
            name='AbonnementEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_abonnement', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.entreprise')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.emailabonne')),
            ],
            options={
                'unique_together': {('email', 'entreprise')},
            },
        ),
        migrations.DeleteModel(
            name='Abonnement',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
