# Generated by Django 5.1.7 on 2025-06-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0019_emailabonne_remove_notification_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='latitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='longitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
